[platformio]
default_envs = nano_atmega328_old_bootloader

[env:nano_atmega328_old_bootloader]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_protocol = arduino
board_upload.speed = 57600
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.5

[env:nano_every]
platform = atmelmegaavr
board = nano_every
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.5
