CREATE TABLE shop_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(32) NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_quantity INTEGER NOT NULL,
    total_price BIGINT NOT NULL,
    recipient_name VARCHAR(50) NOT NULL,
    recipient_phone VARCHAR(30) NOT NULL,
    postal_code VARCHAR(10) NOT NULL,
    address VARCHAR(200) NOT NULL,
    address_detail VARCHAR(200),
    ordered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_shop_order_number UNIQUE (order_number),
    CONSTRAINT fk_shop_order_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT ck_shop_order_status CHECK (
        status IN ('PENDING', 'PAID', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELLED')
    ),
    CONSTRAINT ck_shop_order_total_quantity CHECK (total_quantity > 0),
    CONSTRAINT ck_shop_order_total_price CHECK (total_price > 0),
    CONSTRAINT ck_shop_order_cancelled_at CHECK (
        (status = 'CANCELLED' AND cancelled_at IS NOT NULL)
        OR (status <> 'CANCELLED' AND cancelled_at IS NULL)
    )
);

CREATE TABLE shop_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id VARCHAR(64) NOT NULL,
    category VARCHAR(20) NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    product_emoji VARCHAR(20) NOT NULL,
    product_description VARCHAR(300) NOT NULL,
    unit_price INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal BIGINT NOT NULL,
    package_quantity NUMERIC(10, 2) NOT NULL,
    package_unit VARCHAR(10) NOT NULL,
    sub_category VARCHAR(20),
    CONSTRAINT uq_shop_order_item_product UNIQUE (order_id, product_id),
    CONSTRAINT fk_shop_order_item_order FOREIGN KEY (order_id) REFERENCES shop_order (id) ON DELETE CASCADE,
    CONSTRAINT ck_shop_order_item_unit_price CHECK (unit_price > 0),
    CONSTRAINT ck_shop_order_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_shop_order_item_subtotal CHECK (subtotal = unit_price * quantity),
    CONSTRAINT ck_shop_order_item_package_quantity CHECK (package_quantity > 0)
);

CREATE INDEX idx_shop_order_user_ordered_at
    ON shop_order (user_id, ordered_at DESC, id DESC);

CREATE INDEX idx_shop_order_status
    ON shop_order (status, ordered_at);
