CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL DEFAULT 'TOSS',
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    amount BIGINT NOT NULL,
    customer_key VARCHAR(64) NOT NULL,
    payment_key VARCHAR(200),
    method VARCHAR(50),
    provider_status VARCHAR(30),
    failure_code VARCHAR(100),
    failure_message VARCHAR(300),
    receipt_url VARCHAR(500),
    confirm_idempotency_key VARCHAR(100),
    cancel_idempotency_key VARCHAR(100),
    inventory_deducted BOOLEAN NOT NULL DEFAULT FALSE,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_payment_order UNIQUE (order_id),
    CONSTRAINT uq_payment_payment_key UNIQUE (payment_key),
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES shop_order (id) ON DELETE CASCADE,
    CONSTRAINT ck_payment_provider CHECK (provider IN ('TOSS')),
    CONSTRAINT ck_payment_status CHECK (
        status IN ('READY', 'CONFIRMING', 'PAID', 'FAILED', 'CANCELLED')
    ),
    CONSTRAINT ck_payment_amount CHECK (amount > 0)
);

CREATE INDEX idx_payment_status_updated_at
    ON payment (status, updated_at);
