CREATE TABLE push_registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(2048) NOT NULL,
    platform VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_push_registration_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uq_push_registration_token UNIQUE (token),
    CONSTRAINT ck_push_registration_platform CHECK (platform IN ('ANDROID', 'IOS'))
);

CREATE INDEX ix_push_registration_user_active
    ON push_registration (user_id, active);

CREATE TABLE notification_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(150) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    device_id BIGINT,
    pot_id BIGINT,
    external_ref VARCHAR(200),
    dedupe_key VARCHAR(255) NOT NULL,
    data_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_notification_event_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_event_device
        FOREIGN KEY (device_id) REFERENCES device (id) ON DELETE SET NULL,
    CONSTRAINT fk_notification_event_pot
        FOREIGN KEY (pot_id) REFERENCES pot (id) ON DELETE SET NULL,
    CONSTRAINT ck_notification_event_type
        CHECK (type IN ('SENSOR_ANOMALY', 'DEVICE_OFFLINE', 'IRRIGATION_COMPLETED'))
);

CREATE INDEX ix_notification_event_user_created
    ON notification_event (user_id, created_at DESC);

CREATE INDEX ix_notification_event_condition
    ON notification_event (user_id, dedupe_key, created_at DESC);

CREATE UNIQUE INDEX uq_notification_event_external_ref
    ON notification_event (user_id, type, external_ref);

CREATE TABLE notification_condition_state (
    user_id BIGINT NOT NULL,
    condition_key VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    last_notified_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (user_id, condition_key),
    CONSTRAINT fk_notification_condition_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);
