CREATE TABLE push_registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(2048) NOT NULL,
    platform VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_push_registration_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uq_push_registration_token UNIQUE (token),
    CONSTRAINT ck_push_registration_platform CHECK (platform = 'ANDROID')
);

CREATE INDEX ix_push_registration_user_active
    ON push_registration (user_id, active);

CREATE TABLE notification_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(150) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    device_id BIGINT,
    pot_id BIGINT,
    external_ref VARCHAR(200),
    dedupe_key VARCHAR(255) NOT NULL,
    data_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_notification_event_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_event_device
        FOREIGN KEY (device_id) REFERENCES device (id) ON DELETE SET NULL,
    CONSTRAINT fk_notification_event_pot
        FOREIGN KEY (pot_id) REFERENCES pot (id) ON DELETE SET NULL,
    CONSTRAINT ck_notification_event_type
        CHECK (type IN ('SENSOR_ANOMALY', 'DEVICE_OFFLINE', 'IRRIGATION_COMPLETED'))
);

CREATE INDEX ix_notification_event_user_created
    ON notification_event (user_id, created_at DESC);

CREATE INDEX ix_notification_event_condition
    ON notification_event (user_id, dedupe_key, created_at DESC);

CREATE UNIQUE INDEX uq_notification_event_external_ref
    ON notification_event (user_id, type, external_ref);

CREATE TABLE notification_condition_state (
    user_id BIGINT NOT NULL,
    condition_key VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    last_notified_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (user_id, condition_key),
    CONSTRAINT fk_notification_condition_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE TABLE notification_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    registration_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_delivery_event
        FOREIGN KEY (notification_id) REFERENCES notification_event (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_delivery_registration
        FOREIGN KEY (registration_id) REFERENCES push_registration (id) ON DELETE CASCADE,
    CONSTRAINT uq_notification_delivery UNIQUE (notification_id, registration_id),
    CONSTRAINT ck_notification_delivery_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'SKIPPED', 'FAILED'))
);

CREATE INDEX ix_notification_delivery_pending
    ON notification_delivery (status, available_at, id);
