-- Audit trail for every authorize() call, granted or denied.
--
-- Denials are stored, not just logged: a pot that quietly never gets watered
-- looks identical to a healthy pot unless the refusals are queryable. This is
-- also the table that answers "why did this pot get watered at 3am".
--
-- Deviation from docs/design/edge_ai_hardening.md: the doc numbers this V11,
-- but V11 is telemetry_event and V12-V19 are the commerce migrations, so it
-- lands at V20. The doc's
-- TIMESTAMPTZ is spelled TIMESTAMP WITH TIME ZONE to match every other
-- migration here and to migrate cleanly on H2 in PostgreSQL mode, which the
-- test profile uses.
CREATE TABLE irrigation_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pot_id BIGINT NOT NULL REFERENCES pot (id) ON DELETE CASCADE,
    -- The telemetry event id the decision was based on, so a dose can be
    -- traced back to the reading that caused it.
    correlation_id VARCHAR(64) NOT NULL,
    source VARCHAR(20) NOT NULL,
    sample_observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    soil_moisture_pct DOUBLE PRECISION,
    rule_verdict VARCHAR(20) NOT NULL,
    ai_model_version VARCHAR(50),
    ai_requested_ml INTEGER,
    granted_ml INTEGER,
    deny_reason VARCHAR(30),
    clamp_reason VARCHAR(30),
    command_id VARCHAR(40),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- A decision is exactly one of granted or denied. Without this, a bug that
    -- writes both leaves a row that reads as "watered 80mL because COOLDOWN",
    -- which no later reader can untangle.
    CONSTRAINT ck_irrigation_decision_outcome
        CHECK ((granted_ml IS NOT NULL AND deny_reason IS NULL)
            OR (granted_ml IS NULL AND deny_reason IS NOT NULL))
);

-- Every read of this table is "the recent history of one pot".
CREATE INDEX ix_irrigation_decision_pot_time ON irrigation_decision (pot_id, created_at DESC);
