CREATE TABLE device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_code VARCHAR(6) NOT NULL,
    user_id BIGINT,
    status VARCHAR(10) NOT NULL DEFAULT 'OFFLINE',
    last_seen_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_device_serial_code UNIQUE (serial_code),
    CONSTRAINT uq_device_user_id UNIQUE (user_id),
    CONSTRAINT fk_device_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_device_serial_code_length CHECK (CHAR_LENGTH(serial_code) = 6),
    CONSTRAINT ck_device_status CHECK (status IN ('ONLINE', 'OFFLINE'))
);

INSERT INTO device (serial_code) VALUES ('483920');
