CREATE TABLE cultivation_space (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    space_type VARCHAR(50) NOT NULL,
    area_m2 DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cultivation_space_user_id UNIQUE (user_id),
    CONSTRAINT uq_cultivation_space_device_id UNIQUE (device_id),
    CONSTRAINT fk_cultivation_space_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_cultivation_space_device FOREIGN KEY (device_id) REFERENCES device (id) ON DELETE CASCADE,
    CONSTRAINT ck_cultivation_space_area CHECK (area_m2 > 0)
);
