CREATE TABLE pot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    node_id VARCHAR(64),
    label VARCHAR(100) NOT NULL,
    crop_code VARCHAR(50),
    crop_selected_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(10) NOT NULL DEFAULT 'OFFLINE',
    last_seen_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pot_device FOREIGN KEY (device_id) REFERENCES device (id) ON DELETE CASCADE,
    CONSTRAINT fk_pot_crop FOREIGN KEY (crop_code) REFERENCES crop (code),
    CONSTRAINT ck_pot_status CHECK (status IN ('ONLINE', 'OFFLINE')),
    CONSTRAINT ck_pot_crop_selection CHECK ((crop_code IS NULL AND crop_selected_at IS NULL)
        OR (crop_code IS NOT NULL AND crop_selected_at IS NOT NULL)),
    CONSTRAINT uq_pot_device_node UNIQUE (device_id, node_id)
);

INSERT INTO pot (device_id, label, crop_code, crop_selected_at, status, last_seen_at)
SELECT id, '화분 1', crop_code, crop_selected_at, status, last_seen_at FROM device;
